### ISSUE TITLE
The `Filter` class is missing necessary methods

### ISSUE THREAD

**Issue by hammadmajid** [Isha-khan789/oop-theory-project#3]
Note that in the diagram: the `Filter` class has three methods but are missing from the code.

- filter(Filter f);
- rotate(Direction d);
- crop(Ratio r);

![diagram](https://github.com/Isha-khan789/oop-theory-project/assets/67387019/ce5b2574-3dcc-4259-9517-03ff1e8f5f95)

**Comment by Isha-khan789** [comment]
yeh samjhaoo

**Comment by hammadmajid** [comment]
English

**Comment by Isha-khan789** [comment]
go die

**Comment by hammadmajid** [comment]
```cpp
class Editor : public Image {
	void filter(Filter f);
};
```

Add rest of the functions as mentioned above:


> * rotate(Direction d);
> 
> * crop(Ratio r);
